name: Simple Arduino Compilation

on:
  push:
  repository_dispatch:
    types: [compile-arduino]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/arduino-cli
        arduino-cli core update-index
        arduino-cli core install arduino:avr
    
    - name: Find and compile sketches
      run: |
        mkdir -p builds
        
        # Find all .ino files
        for ino_file in $(find . -name "*.ino" -type f); do
          echo "Found: $ino_file"
          
          # Get sketch name
          sketch_name=$(basename "$ino_file" .ino)
          echo "Compiling: $sketch_name"
          
          # Create proper structure
          mkdir -p "$sketch_name"
          cp "$ino_file" "$sketch_name/$sketch_name.ino"
          
          # Compile
          mkdir -p "builds/$sketch_name"
          arduino-cli compile --fqbn arduino:avr:uno "$sketch_name" --output-dir "builds/$sketch_name" --export-binaries
          
          # Cleanup
          rm -rf "$sketch_name"
        done
        
        # Show results
        find builds/ -name "*.hex" -type f
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: builds/**/*.hex
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add builds/
        git commit -m "Add firmware [skip ci]" || echo "Nothing to commit"
        git push || echo "Nothing to push"
